### ISSUE TITLE
BUG client 

### ISSUE THREAD

**Issue by GamingMineblox** [Androz2091/AtlantaBot#114]
**Please describe the problem you are having in as much detail as possible:**
I self host the bot and have an error when I run an command that has the client tag in it
**To Reproduce**
Run any command with the client tag in it like !partners or !staff
**Expected behavior**
A clear and concise description of what you expected to happen:
Run the command without issues
**Screenshots**
If applicable, add screenshots to help explain your problem:
![image](https://user-images.githubusercontent.com/42892277/67140251-221f5280-f259-11e9-968e-28e05b194ec1.png)

**Further details:**
- Atlanta version:
 - 4.5.0
- discord.js version:
 - latest
- Node.js version:
 - 12.11.0
- Operating system:
 - Windows 10 Home

**Comment by Androz2091** [comment]
Hello,
Try to replace `client.logger.log("Uncaught Promise Error: "+err, "error");`
with `console.error(err);` [here](https://github.com/Androz2091/AtlantaBot/blob/develop/atlanta.js#L62). Then restart the bot. The error in the console should be more explicit.

**Comment by GamingMineblox** [comment]
`[2019-10-19 12:31:47.261]: CMD Gaming Mineblox (356062898008883200) ran command partners
TypeError: Cannot read property 'client' of undefined
    at new MessageEmbed (D:\Koen\Documenten\atlasnet-manager\node_modules\discord.js\src\structures\MessageEmbed.js:13:60)
    at Partners.run (D:\Koen\Documenten\atlasnet-manager\commands\General\partners.js:27:21)
    at module.exports.run (D:\Koen\Documenten\atlasnet-manager\events\message.js:220:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`
