### ISSUE TITLE
all Command not Running

### ISSUE THREAD

**Issue by halubotdc** [Androz2091/AtlantaBot#144]
**Please describe the problem you are having in as much detail as possible:**

**To Reproduce**
node .

**Expected behavior**
A clear and concise description of what you expected to happen:
after running **node.** Everything works smoothly, but when I run all commands **there is no reaction at all or it doesn't run**
for more details, we provide screenshots at the Atlanta command prompt

**Screenshots**
https://snipboard.io/cM5SQ7.jpg

**Further details:**
- atlanta version: https://github.com/Androz2091/AtlantaBot
- discord.js version: 11.5.1
- Node.js version: node-v13.3.0
- Operating system: Windows 10 Pro

**Additional context**
Add any other context about the problem here:

**Comment by Androz2091** [comment]
You must upgrade your Discord.js version from 11.5.1 to 12. Run the following command in your bot's folder:
```sh
npm uninstall discord.js && npm install discordjs/discord.js
```

**Comment by Androz2091** [comment]
It was the problem.
