### ISSUE TITLE
Please remove references to AnIdiotsApi from the docs

### ISSUE THREAD

**Issue by eslachance** [Androz2091/AtlantaBot#145]
https://www.atlanta-bot.fr/installation/windows and https://www.atlanta-bot.fr/installation/linux make reference to "AnIdiots API" with a link to a nonexistent Discord server since the API went offline on September 23rd. It's even removed from the code, https://github.com/Androz2091/AtlantaBot/commit/5d81ee0c10269c4ac2068f9a51505f912e1b0599 , but references are there in the docs. 

This causes some people to join An Idiots Guide, the other server made by the guy that had the API, asking about getting a key and such. Not the end of the world, but it's a bit of an annoyance that could be resolved by fixing the documentation. 

Cheers, 
Evie

**Comment by Androz2091** [comment]
Yes, you're right. I've removed it from the docs. (f5c39adcf7bc65d58260d0504c0853d00011310b)
Thank you
