### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by namekinggamerboy** [Androz2091/AtlantaBot#153]
**Please describe the problem you are having in as much detail as possible:**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen:

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Further details:**
- atlanta version:
- discord.js version:
- Node.js version:
- Operating system:

**Additional context**
Add any other context about the problem here:
![Screenshot_2020-01-01-20-55-07-920](https://user-images.githubusercontent.com/53903319/71642951-14665e80-2cd9-11ea-9933-54c112b2af86.jpeg)
Why show me error :-https://discordapp.com/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fmagic-aspen.glitch.me%2Flogin&scope=identify%20guilds&client_id=656731663107227678 my total setup done

**Comment by Androz2091** [comment]
Can you show your oauth2 application configuration? You will find it here:  
https://discordapp.com/developers/applications/656731663107227678/oauth

**Comment by namekinggamerboy** [comment]
![Screenshot_2020-01-02-07-09-34-288](https://user-images.githubusercontent.com/53903319/71648784-e9a6f500-2d2e-11ea-9064-58eca7691a7d.jpeg) I am setup all but why show me error do idea

**Comment by namekinggamerboy** [comment]
And I am try custom authorhttps://discordapp.com/api/oauth2/authorize?client_id=656731663107227678&redirect_uri=https%3A%2F%2Fmagic-aspen.glitch.me&response_type=code&scope=identify%20guilds so so me error

**Comment by Androz2091** [comment]
You need to set your redirect url to `https://magic-aspen.glitch.me/login`, that's why you're getting an Invalid redirect_uri error. Change it and refresh, it should work

**Comment by Veinify** [comment]
If you guys still getting the error. Try using `https://project-name.glitch.me//login`. Use `//` instead of `/`

**Comment by Androz2091** [comment]
If the website redirects you to `//login` it means your config isn't correct.

**Comment by Veinify** [comment]
I mean... I didn't even change any routes or other stuff like that. if i try using only one `/` it gave me that error again

**Comment by Veinify** [comment]
Oh nvm. I put / at the end of my baseURL
