### ISSUE TITLE
TypeError: giveaways.launch is not a function

### ISSUE THREAD

**Issue by Alpha3235** [Androz2091/AtlantaBot#163]
**Please describe the problem you are having in as much detail as possible:**
getting error in events/ready.js 
the error is [TypeError: giveaways.launch is not a function
at module.exports.run (/app/events/ready.js:45:19)
at Atlanta.client.on.args (/app/alpha.js:34:49)
    at Atlanta.emit (events.js:189:13)]..
and also bot is not showing the status..
**To Reproduce**
N/A
**Expected behavior**
A clear and concise description of what you expected to happen:
N/A
**Screenshots**
If applicable, add screenshots to help explain your problem:
no
**Further details:**
- atlanta version:4.6.4
- discord.js version:12.0.0
- Node.js version:10.15.3
- Operating system:node.js

**Additional context**
Add any other context about the problem here:

**Comment by Androz2091** [comment]
Hello,
Try to downgrade **discord-giveaways** by running `npm install discord-giveaways@2.4.4` in your AtlantaBot folder.

**Comment by Alpha3235** [comment]
should i do npm or is their any codes to change

**Comment by Alpha3235** [comment]
also i am getting this error when i typr help command

TypeError: Cannot read property 'me' of undefined
    at /root/alpha123/helpers/functions.js:58:32
    at new Promise (<anonymous>)
    at Object.supportLink (/root/alpha123/helpers/functions.js:56:16)
    at Help.run (/root/alpha123/commands/General/help.js:85:92)
    at module.exports.run (/root/alpha123/events/message.js:224:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Alpha3235** [comment]
also i am getting emoji error in work.js 
![Screenshot_165](https://user-images.githubusercontent.com/43195493/73743645-1064ab00-4775-11ea-8590-b03fb205ed72.png)

**Comment by Androz2091** [comment]
Are you sure that the members who reacted aren't administrators?

**Comment by Alpha3235** [comment]
yes i am sure

**Comment by Alpha3235** [comment]
i am getting error wjen i use play command 
4|alphabot | TypeError: Cannot convert "null" to int
4|alphabot |     at Object.toWireType (/root/alpha123/node_modules/opusscript/build/opusscript_native_wasm.js:8:47113)
4|alphabot |     at OpusScriptHandler$_encode [as _encode] (eval at new_ (/root/alpha123/node_modules/opusscript/build/opusscript_native_wasm.js:8:36904), <anonymous>:9:26)
4|alphabot |     at OpusScript.encode (/root/alpha123/node_modules/opusscript/index.js:69:28)
4|alphabot |     at Encoder._encode (/root/alpha123/node_modules/prism-media/src/opus/Opus.js:55:25)
4|alphabot |     at Encoder._transform (/root/alpha123/node_modules/prism-media/src/opus/Opus.js:138:30)
4|alphabot |     at Encoder.Transform._read (_stream_transform.js:191:10)
4|alphabot |     at Encoder.Transform._write (_stream_transform.js:179:12)4|alphabot |     at doWrite (_stream_writable.js:453:12)
4|alphabot |     at writeOrBuffer (_stream_writable.js:435:5)
4|alphabot |     at Encoder.Writable.write (_stream_writable.js:326:11)
4|alphabot |     at VolumeTransformer.ondata (_stream_readable.js:727:22)
4|alphabot |     at VolumeTransformer.emit (events.js:321:20)
4|alphabot |     at addChunk (_stream_readable.js:305:12)
4|alphabot |     at readableAddChunk (_stream_readable.js:280:11)
4|alphabot |     at VolumeTransformer.Readable.push (_stream_readable.js:214:10)
4|alphabot |     at VolumeTransformer.Transform.push (_stream_transform.js:152:32)
4|alphabot |     at VolumeTransformer._transform (/root/alpha123/node_modules/prism-media/src/core/VolumeTransformer.js:60:12)
4|alphabot |     at VolumeTransformer.Transform._read (_stream_transform.js:191:10)
4|alphabot |     at VolumeTransformer.Transform._write (_stream_transform.js:179:12)
4|alphabot |     at doWrite (_stream_writable.js:453:12)
4|alphabot |     at writeOrBuffer (_stream_writable.js:435:5)
4|alphabot |     at VolumeTransformer.Writable.write (_stream_writable.js:326:11)
4|alphabot | TypeError: Cannot convert "null" to int
4|alphabot | abort(TypeError: Cannot convert "null" to int). Build with -s ASSERTIONS=1 for more info.
4|alphabot | 
4|alphabot | /root/alpha123/node_modules/opusscript/build/opusscript_native_wasm.js:8
4|alphabot | var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=function(status,toThrow){throw toThrow};Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){ret4|alphabot | abort(TypeError: Cannot convert "null" to int). Build with -s ASSERTIONS=1 for more info.
4|alphabot | (Use `node --trace-uncaught ...` to show where the exception was thrown)

**Comment by Alpha3235** [comment]
also i am getting a very high ping min 1-2k ms of my bot idk y its so much high ping so plzz help me

**Comment by Priyanshu348** [comment]
What host do you use tell me. Or Dm me in discord id "HACKERZ#5686"

**Comment by Alpha3235** [comment]
i am using a GalaxyGate of vpz and also i have send frnd request in discord my name is 'come back'

**Comment by CosmoXxX** [comment]
Use node-opus instead of opusscript

**Comment by thewolf87** [comment]
I am getting error on package.js

**Comment by Androz2091** [comment]
What do you mean? @thewolf87

**Comment by thewolf87** [comment]
Sorry but I fixed it now I am having problem with this it is saying me this.....
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'blague.xyz'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/app/atlanta.js:1:89)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by thewolf87** [comment]
Plz tell me how to fix this

**Comment by Doxx76** [comment]
Moi aussi ça me le fait !

**Comment by Androz2091** [comment]
Run `npm install` and restart the bot.

**Comment by thewolf87** [comment]
Nope I am having same problem can you please join my glitch project and fix error I will give you my discord I'd and send link in dm

**Comment by Priyanshu348** [comment]
Give me your glitch project link thewolf
My Id is HACKER#5686

**Comment by thewolf87** [comment]
Can you fix this

**Comment by Androz2091** [comment]
Atlanta now uses discord-giveaways v3
