### ISSUE TITLE
voiceChannel must be type of VoiceChannel

### ISSUE THREAD

**Issue by Majoramari** [Androz2091/AtlantaBot#171]
**Please describe the problem you are having in as much detail as possible:**
I self host the bot and have an error when I run an music command i have the api on

**To Reproduce**
Run any command !play
**Expected behavior**
A clear and concise description of what you expected to happen:

**Screenshots**
If applicable, add screenshots to help explain your problem:
[image](https://cdn.discordapp.com/attachments/602952740209164292/683751422201823232/1.gif)
**Further details:**
- atlanta version:v4.6.4
- discord.js version:v12.0.0-dev
- Node.js version: v13.9.0
- Operating system: windows 10 64

**Additional context**
Add any other context about the problem here:

**Comment by Androz2091** [comment]
Yes, this is a known bug it will be fixed in v5. You can run `npm install discord-player` and it should fix your problem.

**Comment by Veinify** [comment]
> Yes, this is a known bug it will be fixed in v5. You can run `npm install discord-player` and it should fix your problem.

TypeError: Cannot read property 'isPlaying' of undefined
at Play.run (/app/commands/Music/play.js:30:44)
at module.exports.run (/app/events/message.js:224:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Majoramari** [comment]
> Yes, this is a known bug it will be fixed in v5. You can run `npm install discord-player` and it should fix your problem.

there's alot of issues on music like search results is wrong and if u kick the bot it doesn't realize he is kicked and more i hope if u fix it♥

**Comment by Androz2091** [comment]
Yes, all the bugs are going to be fixed in v5. It will use Lavalink.
