### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Veinify** [Androz2091/AtlantaBot#172]
**Please describe the problem you are having in as much detail as possible:**
I self-host the bot on heroku and i enabled the dashboard but it gave me an error.

**To Reproduce**
Run the bot on heroku

**Expected behavior**
A clear and concise description of what you expected to happen:
I get this error:
2020-03-02T08:35:24.744548+00:00 heroku[web.1]: State changed from starting to crashed
2020-03-02T08:35:24.651216+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-03-02T08:35:24.651216+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-03-02T08:35:24.730872+00:00 heroku[web.1]: Process exited with status 137

**Screenshots**
If applicable, add screenshots to help explain your problem:
![image](https://user-images.githubusercontent.com/59754235/75659280-488bda80-5c9c-11ea-81c9-519afe4f58af.png)

**Further details:**
- atlanta version:4.6.4
- discord.js version:12.0.1
- Node.js version:12.16.1
- Operating system:Heroku

**Additional context**
Add any other context about the problem here:

**Comment by MistikSenpa** [comment]
Their own dashboard is currently down also

**Comment by Veinify** [comment]
EDIT: I fixed it, the error was caused because i used "web" instead of "worker" in Procfile. But i have a really bad question. Why is my dashboard is not showing, i already set up everything but it still not showing up. It just said ip address not found
