### ISSUE TITLE
Bug: checkUnmutes.js | Cannot find property "find" of undefined

### ISSUE THREAD

**Issue by rhearmas** [Androz2091/AtlantaBot#174]
**Issue description:**
Simply having the bot running with no actively muted users spams the console with the following:
```
TypeError: Cannot read property 'find' of undefined
    at Timeout.setInterval [as _onTimeout] (C:\Users\criti\Repositories\atlanta\helpers\checkUnmutes.js:13:26)
```

**Reproduction steps:**
Simply run the bot without having anyone muted.

**Expected behavior**
The code should detect if there is nobody muted, and if so, simply stop running until the next scan starts.

**Further details:**
- atlanta version: latest
- discord.js version: v12 (master)
- Node.js version: v13.11.0
- Operating system: Windows 10 Home 64-bit

**Comment by Androz2091** [comment]
Did you set up the mongo database? Can you show the logs of your bot so we could have more informations? 😅

**Comment by rhearmas** [comment]
I'll have to set up the database; hold on just a second!

**Comment by mystere19052003** [comment]
Even if the database was created, there is this error, i don't know why.

**Comment by rhearmas** [comment]
Yeah; I just installed Mongo on my machine so I can set up my own database. I'm unsure on where to go after having installed Mongo on my machine though 🙁

**Comment by mystere19052003** [comment]
There's nothing to do by leaving to install mongoDB. Except put the connection link to the db in the config file. The code has not been updated for some time. The problem can come from there.

**Comment by rhearmas** [comment]
The best suggestion I have is to modify the code so it detects if there's nobody muted, and if so, completely avoid the attempts to find muted users.

**Comment by mystere19052003** [comment]
It is true that this is the best suggestion to make x).
But Androz will probably help you just for this problem and not modify the code. Why ? Because the next version is not on the same db.

**Comment by rhearmas** [comment]
Ah, I see. Alright. I'll have to see what Androz says about this... I really have no logs to show besides the commands loading, really.

**Comment by mystere19052003** [comment]
I know, I looked and saw that the spam error the console because it can not take all the users of the db to check if they are mutated. Androz will respond later. Good day or good evening.

**Comment by rhearmas** [comment]
Alright! Stay safe; you as well.

**Comment by Androz2091** [comment]
@rhearmas does the message `LOG Connected to the mongo database` appear?

**Comment by mystere19052003** [comment]
The bot lights up, it loads everything, until the no bug. It connects to the db. The Check mutes interval is 5s. Every 5s, the console is spam because find is undefined

**Comment by rhearmas** [comment]
@Androz2091 Yes, that message appears. Everything loads fine, but my issue is what mystere is referring to.

**Comment by mystere19052003** [comment]
I'm talking about the problem you talked about at the start of the issue

**Comment by rhearmas** [comment]
So I found a simple fix to this issue after tweaking the code myself...
I went into the checkUnmutes.js file, and added the following line of code:

```js
if(client.membersData === undefined) return;
```

After having placed this **before** the statement of `muted`, this ended up fixing the issue! I'm hoping others can see this too; thanks to everyone who provided input.

**Comment by mystere19052003** [comment]
👍
