### ISSUE TITLE
Invalid OAuth2 redirect_uri

### ISSUE THREAD

**Issue by AkgunFatih** [Androz2091/AtlantaBot#184]
i set my dashboard:
baseURL:  to "http://localhost",
but when i visit http://localhost it says Invalid OAuth2 redirect_uri

https://discordapp.com/oauth2/authorize?response_type=code&redirect_uri=http://localhost/login&scope=identify guilds&client_id=7024***

i dont understand

**Comment by AkgunFatih** [comment]
fixed by adding oauth redirects in bot settings

**Comment by thekevinava** [comment]
in baseURL you need to put with port

**Comment by AkgunFatih** [comment]
no you don't

**Comment by Crni39** [comment]
What reddirect need goes to bot Oauth2 page?
