### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by thekevinava** [Androz2091/AtlantaBot#194]
**Please describe the problem you are having in as much detail as possible:**
-Music player choose what it wants, if you search something, I thing it reproduces first search it gets, not your choice

-Backup isnt working

**Comment by Androz2091** [comment]
Yes, all these bugs are known and are going to be fixed in the next few days. Thank you for reporting them.

**Comment by thekevinava** [comment]
ahh ok, if I find how to, I'll send here :D

**Comment by thekevinava** [comment]
I found more but I fixed it... I dont remember wich ones now :S

**Comment by Androz2091** [comment]
All right, no problem. If you have found bugs that you know how to fix, you can open a PR 👍

**Comment by thekevinava** [comment]
https://github.com/Androz2091/AtlantaBot/commit/b92fd6ef16beb4c6724eb9259393b65a70df369f#r39501014

**Comment by Androz2091** [comment]
Fixed in v4.7.0
