### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by NocKby** [Androz2091/AtlantaBot#203]
Bonjour Androz,

Etant donné que personne sur le Discord AndrozDev soit en capacité de m'aider, je te pose la question suivante :
Pourquoi mon bot (Code du Atlanta) n'affiche pas son statut ??

Malgré avoir regardé de nombreuses fois le ready.js et que je n'ai rien modifié dessus, je ne trouve pas l'erreur =/

Merci d'avance
Cordialement,

NocKby

**Comment by ssoraa** [comment]
Bojour, ta une erreur dans ta console ? 
### ESSAYE SA DANS LE READY
`client.user.setActivity('ton text');`
