### ISSUE TITLE
minecraft command is no longer working

### ISSUE THREAD

**Issue by SickProdigy** [Androz2091/AtlantaBot#212]
Minecraft command issue

*minecraft ip
In discord use this command

Expected it to bring back
https://i.imgur.com/5MLcXWb.png

In AtlantaBot/commands/General/minecraft.js
Line 70 "json.raw.version.name || json.raw.server_engine"
The .name is undefined, so i just commented it out to work. Not sure if it's a parsing issue or what quite yet. Just testing all commands still. 

**Further details:**
- atlanta version:
- discord.js version:
- Node.js version:
- Operating system:
All newest versions.
Ubuntu 20 lts

**Comment by Androz2091** [comment]
Yes, the minecraft command should be updated to match the new mcapi.us responses.

**Comment by Androz2091** [comment]
Fixed (https://github.com/Androz2091/AtlantaBot/releases/tag/v4.7.0)
