### ISSUE TITLE
The dashboard isn't running.

### ISSUE THREAD

**Issue by suhd00d** [Androz2091/AtlantaBot#214]
The dashboard will not run for some reason. The bot says it's online but the dashboard doesn't load on the open source end.

**Comment by suhd00d** [comment]
As well as on your hosted end

**Comment by Androz2091** [comment]
Are you using the bot on your own computer? If so, did you try to open `http://localhost:8080` in your browser?

**Comment by Androz2091** [comment]
Closed due to inactivity
