### ISSUE TITLE
Peut on utiliser le Dashboard à part ?

### ISSUE THREAD

**Issue by ZerioDev** [Androz2091/AtlantaBot#234]
Bonjour Androz 👋

Est il possible d’utiliser le Dashboard à part ? C’est à dire sans devoir tout télécharger (si vous avez le temps). J’utilise moi meme Mongo DB et le dash étant en Mongo DB cela serait super de pouvoir le récupérer (sans négliger l’apparence qui est superbe à mon goût). 

Une version du dash à part est elle prévue ?

Bonne journée à vous 🙂

**Comment by ssoraa** [comment]
Bonjour, oui il est possible de l'utiliser a part avec quelques modification a faire ;). Si vous avez besoin d'aide merci de me mp sur discord (sora#9258)

**Comment by Androz2091** [comment]
Le dashboard ne sera pas disponible de manière plus simple sur le repo d'Atlanta, car les paramètres ne fonctionneraient pas sans la même base de données. Pour la structure et le code html de base, tu peux utiliser adminlte.
