### ISSUE TITLE
DM Commands

### ISSUE THREAD

**Issue by vBread** [Androz2091/AtlantaBot#253]
**Please describe the problem you are having in as much detail as possible:**
When trying to execute a command in a DM, Atlanta responds with `PREFIX_DM` instead of the respective message.

**To Reproduce**
Type a command in a DM with Atlanta

**Expected behavior**
A clear and concise description of what you expected to happen:
Error message/run the command

**Screenshots**
If applicable, add screenshots to help explain your problem:
![Screen Shot 2020-07-18 at 9 51 47 PM](https://user-images.githubusercontent.com/60681223/87865236-e842c000-c940-11ea-9a88-55799d9fb29b.png)

**Further details:**
- atlanta version: v4.7.0
- discord.js version:
- Node.js version:
- Operating system:

**Additional context**
Add any other context about the problem here:

**Comment by Androz2091** [comment]
Fixed in v4.7.1
