### ISSUE TITLE
[Enhancement] verify-config.js script - check if the dashboard port is open

### ISSUE THREAD

**Issue by HiiZun** [Androz2091/AtlantaBot#258]
**Is your feature request related to a problem? Please describe.**
If the port 3000 for example is used by another nodejs process the script will not warn that. 

**Describe the solution you'd like**
Make the script checking if the port in the config is open or used

**Describe alternatives you've considered**
Check if the dashboard is enabled, if yes check if the port is open by using a module (i don't see another alternative) like [net](https://npmjs.com/package/net)
- [x] example: https://gist.github.com/timoxley/1689041

**Additional context**
None

**Comment by Androz2091** [comment]
Added in v4.7.1
