### ISSUE TITLE
Section premium 

### ISSUE THREAD

**Issue by GalackQSM** [Androz2091/AtlantaBot#283]
Je penser à un truc pas mal, faire une section premium comme sur d'autres bots, genre des commandes ou voir des avantages spécial premium 😏😉

**Comment by Androz2091** [comment]
Atlanta v2 possédait une version premium, qui a été enlevée et ne sera sans doute jamais ajoutée de nouveau. J'ai fait le choix de passer Atlanta open source, et tu peux être certain que si demain je sors une version premium, dans quelques jours il y aura une dizaine de bots "Atlanta Premium Free" qui auront la version premium disponible pour tous. Le premium n'aura donc plus aucune valeur, et seuls les utilisateurs qui veulent faire un don achèteront la version premium. C'est l'inconvénient de l'open source, on peut difficilement donner accès à des fonctionnalités exclusives puisqu'elles sont toutes publiques. Je préfère donc laisser toutes les fonctionnalités gratuites et proposer aux gens de donner quelques euros par mois via [Patreon](https://patreon.com/Androz2091).

**Comment by GalackQSM** [comment]
Oui mes pour nous car ont paye des machine pour le bots etc
