### ISSUE TITLE
Some Command Not Working (Command Category Images - 17)

### ISSUE THREAD

**Issue by shamayunshardul** [Androz2091/AtlantaBot#285]
Command Category  **Images - (17)**
Not working commands
*wasted, *wanted, *triggered, *tobecontinued, *scary, *rip, *mission, *jail, *fire,

**Comment by GalackQSM** [comment]
did you put the amethyst api in the config.js file at line 50?

**Comment by shamayunshardul** [comment]
I tried using Atlanta#6770

**Comment by Androz2091** [comment]
Yes, our Amethyste API key wasn't valid. It is now fixed, and our hosted Atlanta version is now working 👍
Thank you
