### ISSUE TITLE
Redid the entire dashboard

### ISSUE THREAD

**Issue by CarlitoGraal** [Androz2091/AtlantaBot#288]
![nnewdash](https://user-images.githubusercontent.com/19639558/89866690-f66db000-db7d-11ea-8522-1800d6962a68.png)

**Comment by Androz2091** [comment]
Nice @CarlitoGraal! Is your code public?

**Comment by TheGamer456YT** [comment]
👏 nice work, you made the dashboard really nice! Great work again!

**Comment by suhd00d** [comment]
@CarlitoGraal is it public? :)
