### ISSUE TITLE
Cannot Join Emoji server (invalid link) 

### ISSUE THREAD

**Issue by Jordaar** [Androz2091/AtlantaBot#291]
The emoji server link isn't opening.It is showing the following error :-

### **This site can’t provide a secure connection**
emojis.atlanta-bot.fr sent an invalid response.
Try running Windows Network Diagnostics.
**ERR_SSL_PROTOCOL_ERROR**

--------------------------------------------------------------------------------------------------------

### THANK YOU!

**Comment by TheGamer456YT** [comment]
In the meantime @Jordaar, you can join it by clicking [here](https://discord.gg/86n3WKY)

**Comment by Androz2091** [comment]
https://www.atlanta-bot.fr/emojis is now working.
