### ISSUE TITLE
Use Gateway Intents?

### ISSUE THREAD

**Issue by AgreeToMyTerms** [Androz2091/AtlantaBot#296]
Use Discord V12 Gateway Intents, is there any support for this? It reduces the amount of cache as well.

**Comment by Androz2091** [comment]
@AgreeToMyTerms we need a lot of intents to make Atlanta work, and we're not at that level of optimization. That's a good suggestion, but turning off some intents for less ram would make things much more complicated and we wouldn't benefit much.
