### ISSUE TITLE
Dashboard help

### ISSUE THREAD

**Issue by DarkPheonix2122** [Androz2091/AtlantaBot#299]
I need help installing the dashboard, idk what to do, plz help me!!!!!

**Comment by TheGamer456YT** [comment]
Did you encounter any errors? Somethings wrong?
If so, type it here, if on the other hand, you *don't* know how to set it up, go to the official server and ask there!

**Comment by DarkPheonix2122** [comment]
okay

**Comment by DarkPheonix2122** [comment]
@TheGamer456YT i tried to join but this came up
![Screenshot 2020-08-25 at 12 13 41 PM](https://user-images.githubusercontent.com/66898756/91199961-8c502180-e6cc-11ea-90b7-a5414529bb77.png)

**Comment by TheGamer456YT** [comment]
Uhhh, i don't really know how to fix this, so its better off trying to get help on the atlanta server

**Comment by EwoX07** [comment]
it was "525" and now its "526 invalid ssl certificate".
pls fix, or help..?

**Comment by DarkPheonix2122** [comment]
i cant join the atlanta server

**Comment by TheGamer456YT** [comment]
Huh, why @DarkPheonix2122 ? Are you banned or something? You can click [here](https://discord.gg/uxQ5rHW) to join the server tho!

**Comment by Androz2091** [comment]
Also the website is working now https://www.atlanta-bot.fr/

**Comment by DarkPheonix2122** [comment]
by the way, are you going to add a level system?
