### ISSUE TITLE
BUG -- Reload not working + Some emojis aren't loading

### ISSUE THREAD

**Issue by AndrewDisco** [Androz2091/AtlantaBot#300]
**Please describe the problem you are having in as much detail as possible:**
**The reload command isn't working, I attached a file of the response:**
![image](https://user-images.githubusercontent.com/66111825/91307379-8898c980-e7b6-11ea-8c57-eddb54a417a7.png)
When running the command, here's the console:
![image](https://user-images.githubusercontent.com/66111825/91307489-aebe6980-e7b6-11ea-8932-b1d6833501ac.png)

**The eval command returns undefined:**
![image](https://user-images.githubusercontent.com/66111825/91307526-bda51c00-e7b6-11ea-8836-7f04c604c9a6.png)
There's no console output to display.

**Some emojis aren't working:**
![image](https://user-images.githubusercontent.com/66111825/91307607-d9102700-e7b6-11ea-9f1b-a807192cdb68.png)

**Further details:**
- Atlanta version: c85efc8 commit
- discord.js version: 12
- Node.js version: Can't find
- Operating system: Linux

**Extra Info:**
I know that I'm not the only one having these issues. There are other people:
![image](https://user-images.githubusercontent.com/66111825/91308134-871bd100-e7b7-11ea-9ab3-c6596ee899db.png)

**Comment by TheGamer456YT** [comment]
First of all, if you want to use the reload command, you have to provide a command, so that isnt a issue, a simple fix would be verifying if a argument is provided, second of all, eval is the same thing as reload, you have to eval something, and a simple fix would be to see if a argument is provided, and last, yes, the emoji's aren't showing up, you will have to join the emoji server, and even if you do that, those emoji's aren't available, so you will have to make a server and put the emoji's there.

**Comment by AndrewDisco** [comment]
> First of all, if you want to use the reload command, you have to provide a command, so that isnt a issue, a simple fix would be verifying if a argument is provided, second of all, eval is the same thing as reload, you have to eval something, and a simple fix would be to see if a argument is provided, and last, yes, the emoji's aren't showing up, you will have to join the emoji server, and even if you do that, those emoji's aren't available, so you will have to make a server and put the emoji's there.

Thanks for the clarification! Would there be any arguments that you can list for me to evaluate?

**Comment by TheGamer456YT** [comment]
hmmmm, you could try (prefix)eval message.author.username

that's very basic and should return you username!

**Comment by AndrewDisco** [comment]
Thanks for everything! I will close this now.
