### ISSUE TITLE
BUG/Incorrect documentation?

### ISSUE THREAD

**Issue by MistikSenpa** [Androz2091/AtlantaBot#308]
On the installation docs it references for a user to use the YouTube API key for

"SimpleYoutube API key is used to search videos on Youtube (play command)"

But when I checked the config.js I dont see any field related to youtube.

All I see it
apiKeys: {
		// BLAGUE.XYZ: https://blague.xyz/
		blagueXYZ: "XXXXXXXXXXX",
		// FORTNITE TRN: https://fortnitetracker.com/site-api
		fortniteTRN: "XXXXXXXXXXX",
		// FORTNITE FNBR: https://fnbr.co/api/docs
		fortniteFNBR: "XXXXXXXXXXX",
		// DBL: https://discordbots.org/api/docs#mybots
		dbl: "XXXXXXXXXXX",
		// AMETHYSTE: https://api.amethyste.moe
		amethyste: "XXXXXXXXXXX",
		// SENTRY: https://sentry.io (this is not required and not recommended)
		sentryDSN: "XXXXXXXXXXX"
	},

Nothing related to youtube?

**Comment by Androz2091** [comment]
Indeed, it's no longer required. Documentation will be updated. Thank you

**Comment by Androz2091** [comment]
Fixed with [v4.8.0](https://github.com/Androz2091/AtlantaBot/releases/tag/v4.8.0)
