### ISSUE TITLE
List of all bugs I have found so far

### ISSUE THREAD

**Issue by Mistik** [Androz2091/AtlantaBot#312]
Work command emojis dont work (AWARD)
- Music doesnt work
- SupportURL isnt defined (when you do the *invite command it returns null)
- Polls dont work

![image](https://user-images.githubusercontent.com/60430725/93302853-82649e80-f7f2-11ea-8c45-f4b88b7098ca.png)

**Comment by Levminer** [comment]
For the music you need ffmpeg.

**Comment by MistikSenpa** [comment]
So I just need to install it and music will work?

**Comment by Levminer** [comment]
After installing ffmpeg it worked for me

**Comment by MistikSenpa** [comment]
> After installing ffmpeg it worked for me

I installed it and music still doesnt work. Im using the master branch

Could you advise me how you installed it?

I used this
https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-18-04/

**Comment by Levminer** [comment]
I installed it the same way. Test it with `ffmpeg -version`

**Comment by MistikSenpa** [comment]
> I installed it the same way. Test it with `ffmpeg -version`

 ffmpeg -version
ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
configuration: --prefix=/usr --extra-version=0ubuntu0.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100

**Comment by Levminer** [comment]
Try to use version 4.7.1 maybe 4.7.2 is buggy. I have 4.7.1 and its working. https://github.com/Androz2091/AtlantaBot/releases/tag/v4.7.1

**Comment by SickProdigy** [comment]
Mark solved, these are all user errors.

**Comment by Androz2091** [comment]
Fixed
