### ISSUE TITLE
Can't play playlist from youtube

### ISSUE THREAD

**Issue by Levminer** [Androz2091/AtlantaBot#313]
`/*****************************************************************************************************
 * validateURL will be renamed to validateID to match with getPlaylistID in the next release of ytpl *
 *                   set `ytpl.do_warn_deprecate = false` to disable this message                    *
 *****************************************************************************************************/`

I get this error when i want to play a playlist.

**Comment by Androz2091** [comment]
This will be fixed in v4.8.0.

**Comment by Levminer** [comment]
@Androz2091 When?

**Comment by Androz2091** [comment]
In the next few hours

**Comment by Androz2091** [comment]
Fixed with [v4.8.0](https://github.com/Androz2091/AtlantaBot/releases/tag/v4.8.0)
