### ISSUE TITLE
starting with music BUG

### ISSUE THREAD

**Issue by cooldude7407** [Androz2091/AtlantaBot#318]
So im trying to start it and this happens 
![discord player](https://user-images.githubusercontent.com/69735170/94225180-53b98880-fec2-11ea-9b5b-0d11ceed380d.png)

**Comment by Androz2091** [comment]
All right, this is because your Node.js version should be upgraded to v14. I will update the lib so it works with v12 too.

**Comment by cooldude7407** [comment]
Ok
