### ISSUE TITLE
Discord server or emoji server link isn't working

### ISSUE THREAD

**Issue by thecyberpop** [Androz2091/AtlantaBot#320]
Hello!
The support link to the discord support server and emoji server isn't working, so can you update it? 
I really appreciate the hardwork thanks for it !

**Comment by Androz2091** [comment]
Hello
Here is the link for the emojis server : https://www.atlanta-bot.fr/emojis

And here is the server : https://discord.gg/Za9zxTH

**Comment by thecyberpop** [comment]
Oh thanks
