### ISSUE TITLE
BUG commande warn 

### ISSUE THREAD

**Issue by GalackQSM** [Androz2091/AtlantaBot#325]
TypeError: message.guild.members.kick is not a function
    at Warn.run (C:\Users\Administrateur\Desktop\DeltaBotV2\commands\Moderation\warn.js:101:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Hel4gate** [comment]
@GalackQSM  is that your  bot working?

**Comment by GalackQSM** [comment]
> @GalackQSM est-ce que votre bot fonctionne?

yes

**Comment by Hel4gate** [comment]
@GalackQSM  dude i dont know my bot isn't wakeup can you show me your config file if you don't mind I  think there is a problem of mine

**Comment by GalackQSM** [comment]
https://github.com/Androz2091/AtlantaBot/blob/master/config.sample.js
