### ISSUE TITLE
Delay response

### ISSUE THREAD

**Issue by EwoX07** [Androz2091/AtlantaBot#336]
Im running it on 10k+ members, and the execution of the bot delay too much. especially for the moderation commands and anything that access the mongoDB.
it runs smoothly in my private server with 300+- members.

**Comment by Androz2091** [comment]
Hello @EwoX07, are you still experiencing the issue?

**Comment by EwoX07** [comment]
nope, it was discord API update which require a verification after more than 75 servers to toggle the priviliged intents.

and btw, have u put the indonesian translations in it? i sent u dms before -doom

**Comment by Androz2091** [comment]
> nope, it was discord API update which require a verification after more than 75 servers to toggle the priviliged intents.

All right, perfect.

> and btw, have u put the indonesian translations in it? i sent u dms before -doom

This is planned, I'm exporting everything from Crowdin.com

**Comment by EwoX07** [comment]
great, please let me know if u done with it :), ill slide to your dms if u dont mind

**Comment by Androz2091** [comment]
@EwoX07 done 👍  (develop branch)
