### ISSUE TITLE
Welcome messages and autorole stopped working

### ISSUE THREAD

**Issue by boogerstealer** [Androz2091/AtlantaBot#339]
when i hosted the bot myself everything worked fine but the welcomer and autorole seamed not to work there was no error messages and nothing in the console

**Comment by MoonsetValleyRP** [comment]
This also happened to me. Did you ever find aa fix?

**Comment by Androz2091** [comment]
@boogerstealer @MoonsetValleyRP you need to enable the server members intent in your developer portal, in the settings of your application. See https://dis.gd/gwupdate for more details
