### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: Not found

### ISSUE THREAD

**Issue by Unknownio** [Androz2091/AtlantaBot#347]
unhandledPromiseRejectionWarning: Error: Not found  
im getting this error when i try to play music

**Comment by FluxLEET** [comment]
i can help with that whats your discord name and tag

**Comment by Unknownio** [comment]
Yoda#4079

**Comment by Unknownio** [comment]
can u help me or not ?

**Comment by FluxLEET** [comment]
i have added you accept me
