### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by MoonsetValleyRP** [Androz2091/AtlantaBot#351]
I am sorry for bothering you today but I have spent like 3 hours making the welcome message and picture the way I want it, and I have done so many tests for it. When I go to test it by having an account leave then join back, it does not show up. Could anyone help me on how I can make it send the message when someone joins the server.

**Comment by Androz2091** [comment]
Hello, please read #339. And use titles that correctly describe your issue, otherwise it is very difficult for us to maintain the project. Thank you.
