### ISSUE TITLE
Error: Cannot find module './lib/axios'

### ISSUE THREAD

**Issue by Morteza355** [Androz2091/AtlantaBot#356]
![Capture](https://user-images.githubusercontent.com/74528563/102004969-a15bc980-3d2a-11eb-8910-49bb513c2cd1.PNG)
Whats problem?

**Comment by Androz2091** [comment]
Hello, looks like you didn't install canvas. Please use `npm install` and if you still have the problem please follow this tutorial, line by line (and it will work): https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows.
