### ISSUE TITLE
i have a problem with npm modules installation :(

### ISSUE THREAD

**Issue by alphabotshero** [Androz2091/AtlantaBot#358]
![Altanta Issue](https://user-images.githubusercontent.com/72487377/102049194-6a5ae600-3e06-11eb-80a9-ad1030a72977.PNG)

**Comment by Androz2091** [comment]
Hello, indeed you need to start your PowerShell using right-click and "Run as administrator". If you still have issues installing windows-build-tools please use https://androz2091.fr/discord.
