### ISSUE TITLE
⠀⠀⠀⠀

### ISSUE THREAD

**Issue by andybot89** [Androz2091/AtlantaBot#360]

**Comment by Androz2091** [comment]
Do you have any log in the terminal?

**Comment by xxunKn0wnx** [comment]
MongooseError: Operation `members.find()` buffering timed out after 10000ms

**Comment by xxunKn0wnx** [comment]
We need a mongodb base but command don't work

**Comment by andybot89** [comment]
Do I need to simply install MongoDB? It shows MongoDB buffering timeouts for different things and that's it, which makes me assume that I do. I will try running it again with mongoDB, thanks for advance!

**Comment by andybot89** [comment]
Update: Didn't help, still get the MongoDB buffering timeouts and I don't know how to fix them.
