### ISSUE TITLE
Website will not work

### ISSUE THREAD

**Issue by RealMidnight** [Androz2091/AtlantaBot#379]
**Please describe the problem you are having in as much detail as possible:**

**To Reproduce**
Steps to reproduce the behavior: When I clicked on the "Installation Guide" it brought me to an error page saying that the host is down

**Expected behavior**
A clear and concise description of what you expected to happen: it was supposed to go to the installation guide

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Further details:**
- atlanta version:
- discord.js version:
- Node.js version:
- Operating system:

**Additional context**
Add any other context about the problem here:

**Comment by RealMidnight** [comment]
most of the api things in config.sample.js does not work

**Comment by Androz2091** [comment]
Yes, you need to create your own API Keys.
