### ISSUE TITLE
Dashboard BUG

### ISSUE THREAD

**Issue by styleryt** [Androz2091/AtlantaBot#385]
I started bot and add redirect uri in dev. portal, if i will go to the server's Ip, it sends me to the authorization page and with the text "Invalid OAuth2 redirect_uri"

**Comment by Androz2091** [comment]
Hello, did you follow one of these tutorials? 
https://github.com/Androz2091/AtlantaBot/discussions/384
https://github.com/Androz2091/AtlantaBot/discussions/371

**Comment by styleryt** [comment]
Thank you very much: 3 You helped me a lot!
