### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by wahyut** [Androz2091/AtlantaBot#390]
{
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/AtlantaBot/helpers/extenders.js',
    '/home/runner/AtlantaBot/atlanta.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! atlantabot@4.9.2 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atlantabot@4.9.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-02T00_38_03_797Z-debug.log
exit status 1

**Comment by SickProdigy** [comment]
Try running "npm install" in the atlanta.js directory. 

node . seems you don't have node installed maybe? or needs to be updated. Not sure. Debug log is what we need to see.

**Comment by Androz2091** [comment]
Closed due to inactivity
