### ISSUE TITLE
*serverinfo BUG

### ISSUE THREAD

**Issue by SickProdigy** [Androz2091/AtlantaBot#392]
Doesn't produce full member count. I don't think the bot count is quite right either. At least locally on my server. 

Edit:
Also *stats under users: the number shows 9. server count is 4 which is correct, but users is off. 

As replacement I would think guild.membercount would suffice for the first one, but for this one I'm not sure. I'll look more into it and post what i think tomorrow, getting late.

**To Reproduce**
Type *serverinfo for bot command

**Expected behavior**
Will produce a single-digit number

**Further details:**
- atlanta version: 4.9.2

**Comment by Androz2091** [comment]
This will be fixed in the next release

**Comment by TuHiN22** [comment]
also there is an issue with *serverinfo guildname command, it doesn't work whether it should be
