### ISSUE TITLE
Number Command BUG

### ISSUE THREAD

**Issue by TuHiN22** [Androz2091/AtlantaBot#396]
**Please describe the problem you are having in as much detail as possible:**
 *number command is accessible by multiple user at the same time and bot responds to all which can be spammed and eventually abused. though in code there is a condition that only one game can be run at a time in the server . but its not working.
**To Reproduce**
 `currentGames[message.guild.id] = message.guild.id;`
adding this line can fix the issue.

**Expected behavior**
Please add a  **cancel feature** to the number command and whenever someone runs the command in a channel, make it so nobody else can run the command again until the author is done playing the game or cancelled it

**Screenshots**
[Screenshots](https://i.top4top.io/p_1865ud7901.jpg)

**Further details:**
- atlanta version: 4.9.2

**Comment by Androz2091** [comment]
You're right, this will be fixed in the next release

**Comment by TuHiN22** [comment]
> You're right, this will be fixed in the next release

Bro Also check the **additional context** please...

**Comment by Androz2091** [comment]
Please open another issue (one per bug), it's easier for maintenance
Thanks
