### ISSUE TITLE
*welcome *goodbye not posting BUG

### ISSUE THREAD

**Issue by SickProdigy** [Androz2091/AtlantaBot#397]
The commands: 
*welcome
*goodbye
are working, just not posting in the channel.

**To Reproduce**
Have a user join or leave your server.

**Expected behavior**
A post in #general-chat saying Welcome blah blah user blah here etc.

**Screenshots**
Not needed.

**Further details:**
- atlanta version: 4.9.2
- Operating system: linux ubuntu 20

**Additional context**
guildmember events not working? maybe updated in discord version.

**Comment by TuHiN22** [comment]
make sure you have enabled intent for bot from developer portal. 
![Screenshot_2021-02-09-11-51-06-980_com android chrome](https://user-images.githubusercontent.com/23416384/107321688-30882200-6acd-11eb-8dcc-4f6792ea3305.jpg)

**Comment by SickProdigy** [comment]
Fixed, guy above's response worked, just took some time.
