### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by SmaDababaXor** [Androz2091/AtlantaBot#399]
hello so I don't know how to add the redirect_uri if someone wanted to help appreciate it

**Comment by SmokieTheDEV** [comment]
Go to https://discord.com/developers/applications 
**select your bot**
**go to the Ouathurl tab
add new ouath url**
put `http://localhost:8080/api/callback`
Then save it 
Now u'are done :)

**Comment by AyushKurian** [comment]
Hey @SmokieTheDEV That didn't fix it for some reason... is there something I'm doing wrong/

**Comment by SmokieTheDEV** [comment]
> Hey @SmokieTheDEV That didn't fix it for some reason... is there something I'm doing wrong/

Make sure you do
http://localhost:8080 in base url
Then in ouath2 tab
http://localhost:8080/login
http://localhost:8080/auth/callback

**Comment by Androz2091** [comment]
Hello, you can read the following tutorial: https://github.com/Androz2091/AtlantaBot/discussions/371
