### ISSUE TITLE
Invalid redirect url

### ISSUE THREAD

**Issue by SmokieTheDEV** [Androz2091/AtlantaBot#400]
BUT IT IS COMING INVALID URL OUATH
i put the http://localhost:8080/api/callback but when i am going its coming invalid ouath url 

https://media.discordapp.net/attachments/809351726921416714/810850572881494056/Screenshot_45.png?width=842&height=473

https://media.discordapp.net/attachments/809351726921416714/810850536400093194/Screenshot_44.png?width=842&height=473

**Comment by Androz2091** [comment]
Read https://github.com/Androz2091/AtlantaBot/discussions/371 please
