### ISSUE TITLE
Run command for replit

### ISSUE THREAD

**Issue by nettlless** [Androz2091/AtlantaBot#404]
What run command would I use for this in replit?

**Comment by SickProdigy** [comment]
There's only 1 run button? I don't understand what you are asking. Assuming you are talking of repl.it , not sure if it will work right with it, as you need mongodb.

**Comment by Androz2091** [comment]
@SickProdigy is right

**Comment by calamityvfx** [comment]
> @SickProdigy is right

uh you do know replit works with mongodb, right?

**Comment by SickProdigy** [comment]
> > @SickProdigy is right
> 
> 
> 
> uh you do know replit works with mongodb, right?

Since when? Please link also so I don't have to search myself.
I don't use replit so no I would not know. I know 6 months ago it didn't.
