### ISSUE TITLE
Bot Status has │ V 4.10.0

### ISSUE THREAD

**Issue by Chrissuboi** [Androz2091/AtlantaBot#450]
How to i remove this, i cant find it on
![image](https://user-images.githubusercontent.com/83354759/116416478-0c71ec80-a843-11eb-88e5-7a712c8d6c75.png)
 cant find it nowhere or  any configwhen i search it,please help

**Comment by SickProdigy** [comment]
How will you know it's version 4.10.0 though?

**Comment by S1mp1yDucky** [comment]
In the bot files, Navigate to "helpers" then "ready.js" and in line 43 remove `+" | v"+version;`
