### ISSUE TITLE
`guildMemberAdd` and `guildMemberRemove` events are not working

### ISSUE THREAD

**Issue by jaypm123** [Androz2091/AtlantaBot#455]
Bot is not sending welcome and goodbye messages and images

**Comment by Androz2091** [comment]
You should enable the SERVER_MEMBERS intent in the discord developer portal (in your app > bot)

**Comment by jaypm123** [comment]
I have enabled it, but still not working and same with atlanta bot
Atlanta is also not sending welcome and goodbye messages and images

**Comment by muhitrhn** [comment]
Hello @Androz2091,
Can you please look into this issue?
I'm having the same issue here, `welcome` and `goodbye` commands works, but they don't trigger `guildMemberAdd` and `guildMemberRemove` events on user join or leave. Maybe they gets triggered but nothing happens, not even an error on log.

Please look into this, thanks in advance.

**Comment by Androz2091** [comment]
@muhitrhn did you enable the guild members intents?

**Comment by Androz2091** [comment]
Okay, this is now fixed in v4.11.0
