### ISSUE TITLE
load/unload command methods

### ISSUE THREAD

**Issue by Spiderjockey02** [Androz2091/AtlantaBot#456]
in the loadCommand method, what is the use of:
```
if (props.init) {
     props.init(this);
}
```
and in the unloadCommand method:
```
if (command.shutdown) {
    await command.shutdown(this);
}
```

**Comment by Androz2091** [comment]
You can use these properties to run functions on command load/unload

**Comment by Spiderjockey02** [comment]
when searching through the entire project using my text editor, I couldn't find any references to command.shutdown() or props.init(). Are there any examples on what they exactly do?

**Comment by Androz2091** [comment]
For example, you could do the following:
```js
const Command = require("../../base/Command.js"),
	Discord = require("discord.js");

let unloadCounter = 0;
let loadCounter = 0;

class ReloadCounter extends Command {
	constructor (client) {
		super(client, {
			name: "stats",
			dirname: __dirname,
			enabled: true,
			shutdown: () => ++unloadCounter,
			init: () => ++loadCounter
		});
	}

	async run (message, args) {

		message.reply(`this command has been unloaded ${unloadCounter} times and loaded ${loadCounter} times.`)

	}

}
module.exports = ReloadCounter;
```

Actually, no command needs these functions for the moment. They are even not supported by the https://github.com/Androz2091/AtlantaBot/blob/master/base/Command.js file, so I think that the best is to remove them.

**Comment by Spiderjockey02** [comment]
oh I see thank you. Yeah I was confused on why I couln't find any references to these methods.
