### ISSUE TITLE
We are not allowed to join Atlanta-Bot support's server...

### ISSUE THREAD

**Issue by Flattest** [Androz2091/AtlantaBot#457]
Hi ! How can i join de support server of Atlanta ? Cuz i am interessed to know more about the bot. Please, change the discord link from https://discord.atlanta-bot.fr/ to a discord.gg/ invite server ! Thanks for reading that message ^^

Here is one screenshot :
![Origin DNS error](https://user-images.githubusercontent.com/79226546/116969225-6cceb700-aca5-11eb-9b4e-8820e1ebdccb.png)

**Comment by SmokieTheDEV** [comment]
Web error

**Comment by Androz2091** [comment]
This is now fixed in v4.11.0
