### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by JustNoRz** [Androz2091/AtlantaBot#5]
voial donc j'utilise la base de atlanta et le dash pour mon bot mais j'ais un problème avec le dash quand je me connect au dash , la redirection ne marche aps je reste bloquer infiniment sur la page oauth de discord 

Et si j'annule je tombe sur sa : 
![image](https://user-images.githubusercontent.com/36740287/58375025-3aa96c00-7f4a-11e9-8854-e0f338d7f648.png)

**Comment by Androz2091** [comment]
Bonjour
Vérifie les paramètres de ton application Discord
Si tu héberges le dashboard en local, vérifie que l'URL de callback est définie sur http://localhost:8080/api/discord/login
Si ça ne marche pas, peux tu préciser un peu plus ton problème ? Est ce que tu as des erreurs dans la console ?

**Comment by JustNoRz** [comment]
nop je suis sur vps , l'url de mon calback est ok je vois pas d'ou vient le soucis aupire si tu peut discord?

**Comment by Androz2091** [comment]
Cette erreur est due au fait que le bot ne trouve pas le serveur support. Vérifie que le fichier de configuration soit correctement rempli et que le bot soit bien sur le serveur défini.
Sinon, tu peux modifier le code en supprimant la partie qui charge les rôles de l'utilisateur dans le fichier website/dashboard/routes/panel.js
Et oui je suis disponible sur Discord (Androz#7209)

**Comment by JustNoRz** [comment]
effectivement , le bot n'etais pas sur le serveur de support merci ^^ de ta reponse rapide et fonctionel
