### ISSUE TITLE
Fails to load 3 music commands

### ISSUE THREAD

**Issue by Jakeonator03** [Androz2091/AtlantaBot#512]
When loading the bot it fails to load 3 commands, the commands "back.js" "skip.js" and "stop.js"

![Screenshot 2021-07-08 220406](https://user-images.githubusercontent.com/63820503/124990585-7e7f6280-e038-11eb-8b23-fa0f0266d5b0.png)

**Comment by Androz2091** [comment]
Fixed on master branch

**Comment by Jakeonator03** [comment]
I was on the master branch

**Comment by Androz2091** [comment]
Clone it again and it will work
