### ISSUE TITLE
I made a request from how to fix but is is already 12+

### ISSUE THREAD

**Issue by TeunHessels** [Androz2091/AtlantaBot#515]
![image](https://user-images.githubusercontent.com/52382388/125166489-c5359f80-e193-11eb-9eaa-ad669fc5d71d.png)
![image](https://user-images.githubusercontent.com/52382388/125166556-13e33980-e194-11eb-9c8c-8ab1d01610ca.png)

**Comment by Androz2091** [comment]
The comment was not entirely right, v14 is required

**Comment by TeunHessels** [comment]
ok

**Comment by S1mp1yDucky** [comment]
close this please
