### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by StudNastty** [Androz2091/AtlantaBot#518]
make a full detailed guide on how to host on a vps with a custom domain

**Comment by Androz2091** [comment]
You should read https://github.com/Androz2091/AtlantaBot/discussions/371

**Comment by StudNastty** [comment]
thats not a real detailed guide lol

**Comment by StudNastty** [comment]
nvm i was on the wrong one GG

**Comment by StudNastty** [comment]
still cant seem to get it to work im using my actual domain instead of the dashboard.mydomain becvause i dont want it to say dashboard
