### ISSUE TITLE
Release of discord.js 13

### ISSUE THREAD

**Issue by le-show-de-didoub74** [Androz2091/AtlantaBot#524]
Yesterday, i went install Atlanta on my server but when i do npm i. it' discord.js 13 installed not discord.js 12.5.3 so you have to modify you're package manager from discord.js to disord.js@12.5.3

**Comment by Androz2091** [comment]
Hello,
Atlanta is using Discord.js v13-dev

**Comment by SickProdigy** [comment]
I'm also having this issue trying to update to atlanta 4.12, the discord version I have locally is 13, but it is wanting to add 12 for some reason, have trying installing 12 npm install discord.js12@npm:discord.js@12.5.3
Then i run into another issue, 

`App [sgdb4.12:4] starting in -fork mode-
22:37:56 PM2         | App [sgdb4.12:4] online
22:37:56 4|sgdb4.12  | 2021-07-24T22:37:56: TypeError: Joker is not a constructor
22:37:56 4|sgdb4.12  | 2021-07-24T22:37:56:     at new Atlanta (/home/discord/atl4.12/AtlantaBot-4.12.0/base/Atlanta.js:64:17)
22:37:56 4|sgdb4.12  | 2021-07-24T22:37:56:     at Object.<anonymous> (/home/discord/atl4.12/AtlantaBot-4.12.0/atlanta.js:22:11)
22:37:56 4|sgdb4.12  | 2021-07-24T22:37:56:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
22:37:56 4|sgdb4.12  | 2021-07-24T22:37:56:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
`

npm audit now

` npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
No fix available
node_modules/axios
  amethyste-api  <=1.1.4
  Depends on vulnerable versions of axios
  node_modules/amethyste-api

2 high severity vulnerabilities
`

The Discord version problem went away, but now these issues are here but doesn't make sense with the error for me. Or I'm not understanding something right. 

Any help would be appreciated.

using ubuntu 20 to host with node js. 

Have run npm install and to no avail, npm install --force doesn't seem to work either.

**Comment by 11TStudio** [comment]
> I'm also having this issue trying to update to atlanta 4.12, the discord version I have locally is 13, but it is wanting to add 12 for some reason, have trying installing 12
> `npm install discord.js12@npm:discord.js@12.5.3`
> __
> Then i run into another issue,
> `App [sgdb4.12:4] starting in -fork mode- 22:37:56 PM2 | App [sgdb4.12:4] online 22:37:56 4|sgdb4.12 | 2021-07-24T22:37:56: TypeError: Joker is not a constructor 22:37:56 4|sgdb4.12 | 2021-07-24T22:37:56: at new Atlanta (/home/discord/atl4.12/AtlantaBot-4.12.0/base/Atlanta.js:64:17) 22:37:56 4|sgdb4.12 | 2021-07-24T22:37:56: at Object.<anonymous> (/home/discord/atl4.12/AtlantaBot-4.12.0/atlanta.js:22:11) 22:37:56 4|sgdb4.12 | 2021-07-24T22:37:56: at Module._compile (internal/modules/cjs/loader.js:1063:30) 22:37:56 4|sgdb4.12 | 2021-07-24T22:37:56: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)`
> __
> npm audit now
> `
> npm audit report
> 
> axios <0.21.1
> Severity: high
> Server-Side Request Forgery - https://npmjs.com/advisories/1594
> No fix available
> node_modules/axios
> amethyste-api <=1.1.4
> Depends on vulnerable versions of axios
> node_modules/amethyste-api
> 
> 2 high severity vulnerabilities
> `
> __
> The Discord version problem went away, but now these issues are here but doesn't make sense with the error for me. Or I'm not understanding something right.
> 
> using ubuntu 20 to host with node js.
> 
> Have run npm install and to no avail, npm install --force doesn't seem to work either.
> 
> Hope this sheds more light on my issue.

Try to clone fresh from the master... And just run `npm i` or `yarn`
And please make sure you have node 14+
Close the issue ticket if this was already been fixed.

**Comment by SickProdigy** [comment]
ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: atlantabot@4.12.0
npm ERR! Found: discord.js@13.2.0-dev
npm ERR! node_modules/discord.js
npm ERR!   discord.js@"discordjs/discord.js" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer discord.js@"^12.0.0" from discord-paginationembed@2.1.0
npm ERR! node_modules/discord-paginationembed
npm ERR!   discord-paginationembed@"^2.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/discord/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/discord/.npm/_logs/2021-09-07T01_18_04_186Z-debug.log


This is what I get running npm i
