### ISSUE TITLE
invite link is invalid

### ISSUE THREAD

**Issue by KainesLaw** [Androz2091/AtlantaBot#550]
invalid invite: https://emojis.atlanta-bot.fr

in emojis.json

**Comment by iiAlanii** [comment]
Here you go:
https://discord.gg/KvvpzcFden

This is the discord server for the emojis!

**Comment by iiAlanii** [comment]
> invalid invite: https://emojis.atlanta-bot.fr
> 
> in emojis.json

Here you go:
https://discord.gg/KvvpzcFden

This is the discord server for the emojis!

**Comment by 11TStudio** [comment]
Fixed in https://github.com/Androz2091/AtlantaBot/pull/555

**Comment by S1mp1yDucky** [comment]
Atlanta Discord Server: https://discord.gg/fHsDX4GHCb

Atlanta Emojis Server: https://discord.gg/cUhmyuC3jy
