### ISSUE TITLE
Atlanta invite link not working.

### ISSUE THREAD

**Issue by lidistat67** [Androz2091/AtlantaBot#552]
Hello there. The atlanta invite website is not working. Please update it or send an invite. Thank you.
![image](https://user-images.githubusercontent.com/44528553/130836260-d2b41eb5-efe7-4f23-a0ea-e68608e7686b.png)

**Comment by 11TStudio** [comment]
Fixed in https://github.com/Androz2091/AtlantaBot/pull/555

**Comment by S1mp1yDucky** [comment]
Atlanta Discord Server: https://discord.gg/fHsDX4GHCb

Atlanta Emojis Server: https://discord.gg/cUhmyuC3jy
