### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mespeczek** [Androz2091/AtlantaBot#57]
Error after starting bot ( Master Branch )
![https://cdn.discordapp.com/attachments/569977794201649182/612740169497444409/Screenshot_2019-08-18-22-09-29.png](https://cdn.discordapp.com/attachments/569977794201649182/612740169497444409/Screenshot_2019-08-18-22-09-29.png)

**Comment by xixi52** [comment]
Hi, you’re config file content a apikey empty ? 
Discord.js is version 12?

**Comment by Androz2091** [comment]
Hello @Mespeczek
I know what's the problem and I will fix it 😉
Please use the stable branch, which has no problem

**Comment by Androz2091** [comment]
It works now 👌
