### ISSUE TITLE
How to add other language to dashboard

### ISSUE THREAD

**Issue by Mespeczek** [Androz2091/AtlantaBot#59]
In title

**Comment by xixi52** [comment]
the only languages available at the moment are French ans English

**Comment by xixi52** [comment]
For add language open a pull request with a file in folder /languages/language.js

**Comment by Mespeczek** [comment]
How to implement this for dashboard?

**Comment by Mespeczek** [comment]
I have already added a language, but it cannot be changed

**Comment by Androz2091** [comment]
You can duplicate the code currently used for French and English to add a button for your language. But yes, currently, buttons are not automatically added...
https://github.com/Androz2091/AtlantaBot/blob/47cbd6db7b7433043176ba419f2871f1238b548f/dashboard/views/guild.ejs#L67

**Comment by Mespeczek** [comment]
I mean dashboard language... not guild language...

**Comment by Androz2091** [comment]
That's more complicated since there's only one " switch language " button.
If you want to do this, you will need to have more knowledge because it is not currently possible easily

**Comment by Mespeczek** [comment]
ok

**Comment by Mespeczek** [comment]
And is there option for change bot dashboard color?

**Comment by Androz2091** [comment]
No, there is no customization possible via the interface itself. But you can modify the css as you wish.
