### ISSUE TITLE
update the code to v13

### ISSUE THREAD

**Issue by Mr-aahir** [Androz2091/AtlantaBot#596]
please update the code to v13 as this is a very old code, btw thanks for putting it as source code!

**Comment by uaktags** [comment]
what code is "very old code"?
v13 requires node 16.6 which is Jul 2021.
v13 itself was released Aug 2021
last packaged release was May 2021.

It's now November of 2021. "Very old" probably isn't the word.

The last commits have started adding v13 support and its trivial at best to get the scopes added for invite to work and to fix the .array() issues.
