### ISSUE TITLE
Problème de démarrage a cause de Quick.db

### ISSUE THREAD

**Issue by MIMIGAMING83** [Androz2091/AtlantaBot#7]
Bonjour j'aimerai faire par d'un problème de quick.db au démarrage du bot voici l'erreur Quickdb.init("./data/atlanta.sqlite"),

        ^

TypeError: Quickdb.init is not a function

**Comment by SkyLineDev** [comment]
Bonjour MIMIGAMING83,
Ceci n'est pas une erreur, Androz utilise une version un peu "modifié" (si je puis dire) de quick.db.
Sur ce git : https://github.com/Androz2091/quick.db tu obtiendras sûrement des reponses.

Cordialement, SkyLine Support de Atlanta.
Discord de Atlanta => https://discord.gg/2vyCyDn

**Comment by MIMIGAMING83** [comment]
Je suis déjà sur le discord de Atlanta, comment es que je pourrai importer cette version modifié sur Glitch ?

**Comment by SkyLineDev** [comment]
Installé quick.db, Tools => Full Page Console.
cd node_modules/quick.db/bin
rm -rf handler.js
wget https://raw.githubusercontent.com/Androz2091/quick.db/glitch/bin/handler.js

**Comment by Androz2091** [comment]
Bonjour 
Il est possible d'installer directement le module en tapant `npm install Androz2091/quick.db`

**Comment by Androz2091** [comment]
D'ici quelques jours, Quickdb ne sera plus utilisé, il faudra seulement installer mongoose.
L'installation de mongoose est plus rapide et plus facile.

**Comment by MIMIGAMING83** [comment]
Je n'ai pas npm sur Glitch malheureusement

**Comment by JustNoRz** [comment]
si il faut juste aller dans la console glitch ou dans le package.json et cliquer sur rechercher

**Comment by JustNoRz** [comment]
![image](https://user-images.githubusercontent.com/36740287/60402713-955e6500-9b93-11e9-86a4-b77ed829a233.png)
![image](https://user-images.githubusercontent.com/36740287/60402716-a1e2bd80-9b93-11e9-95ab-3e7643d41875.png)

**Comment by MIMIGAMING83** [comment]
sur la console de Glitch il n'y a pas encore npm c'est un administrateur des container qui me l'a dit et le package ne permet pas de trouver des versions modded si elle n'est pas submit sur le site de npm

**Comment by MIMIGAMING83** [comment]
D'ailleurs si le screen viens de toi tu devrai cliquer sur les 6 package affichées sa te les mettrai a jour...

**Comment by Androz2091** [comment]
Je ne connais pas bien Glitch mais j'imagine que tu as un accès FTP  ? Si c'est le cas, il faut que tu télécharges la version modifiée de quickdb ici : https://github.com/Androz2091/quick.db et que tu l'upload dans ton dossier node_modules

**Comment by Androz2091** [comment]
De toute façon je compte mettre ma version de quickdb sur npm (ça donnera `npm i @Androz2091/quick.db`) puisque mes pull requests n'ont obtenu aucune réponse jusque là auprès de quickdb 😕

**Comment by JustNoRz** [comment]
![image](https://user-images.githubusercontent.com/36740287/60429838-3bde5080-9bfc-11e9-94cb-63f6d4fdeb3e.png)

**Comment by JustNoRz** [comment]
Oui le screen vient de moi mais c'est un ancien projet que j'ais abandoner

**Comment by Androz2091** [comment]
Je ferme ce ticket car malheureusement je ne peux rien faire pour ce problème, il faut voir si le support de Glitch peut faire quelque chose :\
Si ce n'est pas le cas, je te conseille d'attendre qu'Atlanta soit entièrement développé avec mongoose. 
Et si Glitch ne permet pas d'utiliser mongoose, laisse tomber et passe sur un VPS si tu as les moyens d'en louer un (sinon Heroku est gratuit pour 500mb de ram). 
Bonne journée
