### ISSUE TITLE
problem with guildonly

### ISSUE THREAD

**Issue by Maddcat** [Androz2091/AtlantaBot#8]
if i set guildonly on false and i try to run a command in dm's its still doesn t work

**Comment by Androz2091** [comment]
Do you have any errors in the console?

**Comment by Maddcat** [comment]
no...

**Comment by Maddcat** [comment]
I've tried to create a command for staff applications, and if the person was using the command, he received some private messages that he had to answer, but it does not work ...

**Comment by Androz2091** [comment]
🤔 Can I see your code? Just the part about this command

**Comment by Maddcat** [comment]
yes, check pm on discord

**Comment by Androz2091** [comment]
Problem solved (It came from the command code and not from Atlanta)
