### ISSUE TITLE
Help ?

### ISSUE THREAD

**Issue by LunaiDiscord** [Androz2091/AtlantaBot#9]
Bon apparemment il faut ouvrir une issue ;-; 
Bon, je n'arrive pas à installer le module, bref je comprend rien et ça me fait rager....

**Comment by Androz2091** [comment]
Oui, il faut ouvrir une issue en cas de problème. Mais si le problème concerne un module, il est logique d'aller ouvrir une issue **sur le repo du module** et non pas sur le premier repo github sur Google... :neutral_face:

Si le problème concerne **discord giveaways** c'est [ici](https://github.com/Androz2091/discord-giveaways) et si le problème concerne **discord backup** c'est [ici](https://github.com/Androz2091/discord-backup).

Merci et bonne journée
